### ISSUE TITLE
Support storing events in the database in CloudEvents format

### ISSUE THREAD

**Issue by liamwh** [serverlesstechnology/cqrs#65]
[CloudEvents](https://github.com/cloudevents/spec) aims to be the universal standard for event schemas.

There is an [SDK for Rust](https://github.com/cloudevents/sdk-rust).

It would be fantastic if we could ensure the events published by the framework are serialised into the database as a CloudEvent type with the data in the data field.

Additionally, I would advise using the [ULID](https://github.com/oklog/ulid) crate for the ID if you're open to this suggestion.

**Comment by aurelien-clu** [comment]
I also find `ULID` to be more useful.

If need be I could do PRs (to every CQRS repo) adding a feature flag to enable `ULID` instead of `UUID`.

with `UUID` (no difference / no breaking change):

```toml
cqrs-es = "0.x"
postgres-es = "0.x"
```

with `ULID`:
```toml
cqrs-es = {version = "0.x", features = ["ulid"]}
postgres-es = {version = "0.x", features = ["ulid"]}
```
